name: Build and deploy to Amazon ECS in ShureWeb Old Account

on:
  workflow_call:
    inputs:
      aws_account_id:
        description: The ID of the AWS account
        required: true
        type: string
      deploy_target:
        description: "The deploy environment run the task for: `dev`, `stage` or `prod`"
        required: true
        type: string

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/shure-gms-githubactions-role
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Upload Lambda
      id: upload-lambda
      run: |
        make ci DEPLOY_TARGET=${{ inputs.deploy_target }}